### ISSUE TITLE
vendor/vendor.json?

### ISSUE THREAD

**Issue by gliptak** [hashicorp/terraform-provider-scaffolding#1]
Could current ```vendor/vendor.json``` added to this repo?

I ended up copying from https://github.com/terraform-providers/terraform-provider-null/blob/master/vendor/vendor.json

Thanks

**Comment by kmoe** [comment]
We now recommend Terraform providers use [Go modules](https://github.com/golang/go/wiki/Modules), vendoring their dependencies using `go mod vendor`.

I've updated the README to this effect.
