### ISSUE TITLE
Terraform Custom Provider Use Factories to Test

### ISSUE THREAD

**Issue by fdmsantos** [hashicorp/terraform-provider-scaffolding#79]
Hi there,

I’m creating a new Provider, but i have some doubts in provider Factories.

I’m following terraform-provider-scaffolding so in provider_test.go i have the following:

```
var providerFactories = map[string]func() (*schema.Provider, error){
    "acdcn": func() (*schema.Provider, error) {
        return New("dev")(), nil
    },
}

```

Then in resource test file i would like access to Provider to be able to use my api client to delete the created resource. I’m trying the following:

```
provider, err := providerFactories["acdcn"]()

apiClient := provider.Meta().(*client.Client)
```

But the provider.Meta() is always nil. How i can access to my api client configured in provider?

The Test works well, the resource is created, but i’m unable to destroy the resource inside function configured in CheckDestroy.

Thanks

**Comment by fdmsantos** [comment]
Hi,

I notice that i misunderstood the meaning of CheckDestroy key. The test automatically runs the delete resource operation. So that solves my problem. But i maintain the question, how can i access to my api client?

**Comment by bflad** [comment]
Hi @fdmsantos 👋  Thank you for reaching out. If you are new to Terraform provider development, you may find the [Plugin Development section of the Terraform documentation](https://www.terraform.io/docs/plugin/) contains some helpful information about various parts of code development and testing. In particular, the SDK version 2 section (which is the framework the current terraform-provider-scaffolding template repository is based off) contains a [writeup on writing custom acceptance test checks](https://www.terraform.io/docs/extend/testing/acceptance-tests/teststep.html#custom-check-functions).

What is omitted there, however, is the possibility to have a variable containing a separate instance of the provider, e.g.

```go
// This provider can be used in testing code for API calls without requiring
// the use of saving and referencing specific ProviderFactories instances.
//
// PreCheck(t) must be called before using this provider instance.
var testAccProvider *schema.Provider = New("test")
```

Then the [`TestCase.PreCheck` function](https://www.terraform.io/docs/extend/testing/acceptance-tests/testcase.html#precheck) can be used to configure that separate instance of the provider, e.g.

```go
// Updating provider_test.go
func testAccPreCheck(t *testing.T) {
	err := testAccProvider.Configure(context.Background(), terraform.NewResourceConfigRaw(nil))

	if err != nil {
		t.Fatal(err)
	}
}
```

Acceptance test code can then reference the provider client: `testAccProvider.Meta().(*ExampleClient)` (type asserted to the correct type for your provider).

---

There are likely other or potentially better ways to accomplish this, but that should hopefully get you started.

Please note that this repository is only typically watched by those maintaining this template repository code for bug reports and feature requests. If you are interested in asking questions related to provider development, it is likely better to reach out on the [HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) where there are far more developers looking to answer questions. 👍
