### ISSUE TITLE
Publishing releases to Terraform Registry stopped working

### ISSUE THREAD

**Issue by dentarg** [hashicorp/terraform-provider-scaffolding#82]
Sorry for opening this here, but it [seems impossible](https://discuss.hashicorp.com/t/community-office-hours-terraform/16849/12) to [reach](https://discuss.hashicorp.com/t/unable-to-resync-provider/30706/3) `terraform-registry@hashicorp.com` (we've [emailed too](https://support.hashicorp.com/hc/en-us/requests/60410)).

We are not able to publish new versions to [cloudamqp/cloudamqp](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest). It started with a release that wasn't picked up by the registry, similar to https://github.com/hashicorp/terraform/issues/27533.

In my efforts to try to solve that, I [read the following](https://www.terraform.io/docs/registry/providers/publishing.html#webhooks) and removed the webhook from our repo, hoping I would be able to re-add it.

>If the webhook is missing or not functioning, you can use the Resync button on the provider settings page. First, remove any existing webhooks for registry.terraform.io. Then, click the Resync button on the Terraform Registry's provider settings page. A new webhook should be created.

Problem is, I can't see any Resync button anywhere. How can we get the webhook back? How can get publishing releases to Terraform Registry working again?

Thanks for your time.

---
cc @bflad @paddycarver sorry to mention you, but I saw you were active here yesterday and I'm a bit desperate to be honest

**Comment by redeux** [comment]
Hi @dentarg, I'm sorry to hear about your experience with the Registry. I spoke to the team and they were able to resync your provider. Since this isn't the appropriate channel for this request (although I understand why you used it in this case), I'm going to go ahead and close this issue. Thank you for your patience.
