### ISSUE TITLE
The page of “Writing Custom Providers” DOES NOT exist

### ISSUE THREAD

**Issue by qiuxin** [hashicorp/terraform-provider-scaffolding#88]
The page of “Writing Custom Providers” DOES NOT exist which is describe in  “These files contain boilerplate code that you will need to edit to create your own Terraform provider. A full guide to creating Terraform providers can be found at Writing Custom Providers.”

**Comment by bflad** [comment]
Hi @qiuxin 👋  Thank you for writing in about this issue and sorry for the frustration. It appears that the Terraform website migration to its new platform last month did not carry over this existing redirect. The corrected link is https://learn.hashicorp.com/collections/terraform/providers and we will update the README (and likely the website redirect) accordingly. Thank you again for pointing this out.
